[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "openssl_1_1"]

[phases.install]
cmds = [
  "npm ci",
  "cd src/frontend && npm ci"
]

[phases.build]
cmds = [
  "npm run build",
  "cd src/frontend && npm run build",
  "npx prisma generate"
]

[start]
cmd = "npm run start"

